server:
  port: 8289

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8299
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    propagation:
      type: w3c,b3

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        provider:
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
          cma:
            token-uri: ${CMA_API_OAUTH_URL}
        registration:
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          cma:
            client-id: ${CMA_API_OAUTH_CLIENT_ID}
            client-secret: ${CMA_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

services:
  maat-api:
    base-url: ${MAAT_API_BASE_URL}
    assessments-domain: ${services.maat-api.base-url}/api/internal/v1/assessment
    hardship-endpoints:
      hardship-detail-url: ${services.maat-api.assessments-domain}/hardship/repId/{repId}/detailType/{detailType}
      persist-hardship-url: ${services.maat-api.assessments-domain}/hardship
      hardship-url: ${services.maat-api.assessments-domain}/hardship/{hardshipId}
    financial-assessment-endpoints:
      search-url: ${services.maat-api.assessments-domain}/financial-assessments/{financialAssessmentId}
  cma-api:
    base-url: ${CMA_API_BASE_URL}
    means-assessments-domain: ${services.cma-api.base-url}/api/internal/v1/assessment/means
    cma-endpoints:
      full-assessment-threshold-url: ${services.cma-api.means-assessments-domain}/fullAssessmentThreshold/{assessmentDate}

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.hardship
  api-docs:
    path: open-api/api-docs

  swagger-ui:
    path: open-api/swagger-ui.html
    operationsSorter: method

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}
