# Default values for laa-crime-hardship.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-crime-hardship-dev-ecr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

sentry_dsn: https://f53c1271fd174468871ee12406179f06@o345774.ingest.sentry.io/4505352950710272
aws_region: eu-west-2

java:
  host_env: test

jwt:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_JqMRbcAmZ

maatApi:
  baseUrl: https://maat-cd-api.tst.legalservices.gov.uk
  oauthUrl: https://maat-cd-api-tst.auth.eu-west-2.amazoncognito.com/oauth2/token
  clientId: 74ke8igol2op569oq5d7a75ao6
  clientSecret: lmikvn4lpse0a3g0tnv8gh3lm9hr9b6abjororncc4as9uo0704

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "circleci"

service:
  type: ClusterIP
  port: 8189

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "laa-crime-hardship-laa-crime-hardship-test-green"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
  externalAnnotations: {}
  hosts:
    - host: laa-crime-hardship-test.apps.live.cloud-platform.service.justice.gov.uk
      paths: ["/"]
  tls: []
  className: default

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8199
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5