version: 2.1

orbs:
  snyk: snyk/snyk@1.4.0
  aws-cli: circleci/aws-cli@4.0.0 # use v4 of this orb
  aws-ecr: circleci/aws-ecr@8.2.1 # this orb doesn't support OIDC v2, so we use aws-cli to authenticate

_snyk_options: &snyk_options
  project: "${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}"
  organization: "legal-aid-agency"
  severity-threshold: "critical"
  fail-on-issues: true
  monitor-on-build: false
  token-variable: SNYK_TOKEN
  additional-arguments: --policy-path=.snyk

# ------------------
# EXECUTORS
# ------------------
executors:
  cloud-platform-executor:
    resource_class: small
    docker:
      - image: ministryofjustice/cloud-platform-tools
    working_directory: ~/laa-crime-hardship/crime-hardship
  build-executor:
    docker:
      - image: cimg/openjdk:17.0.4
    working_directory: ~/laa-crime-hardship/crime-hardship

# ------------------
# COMMANDS
# ------------------
commands:
  deploy-to:
    description: >
      Deploy image to the specified environment
    parameters:
      environment:
        description: Destination environment
        type: string
      token:
        description: CircleCI Service account token
        type: string
    steps:
      - checkout
      - run:
          name: Decrypt secrets
          command: |
            echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
            git-crypt unlock git-crypt.key
      - run:
          name: Authenticate with cluster
          command: |
            echo -n ${K8S_CLUSTER_CERT} | base64 -d > ./ca.crt
            kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://${K8S_CLUSTER_NAME}
            kubectl config set-credentials circleci --token=<< parameters.token >>
            kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci --namespace=laa-crime-hardship-<< parameters.environment >>
            kubectl config use-context ${K8S_CLUSTER_NAME}
            kubectl --namespace=laa-crime-hardship-<< parameters.environment >> get pods
      - run:
          name: Upgrade helm chart
          command: |
            helm upgrade laa-crime-hardship ./helm_deploy/laa-crime-hardship/. \
                          --install --wait \
                          --namespace=laa-crime-hardship-<< parameters.environment >> \
                          --values ./helm_deploy/laa-crime-hardship/values-<< parameters.environment >>.yaml \
                          --set image.tag="${CIRCLE_SHA1}"

# ------------------
# JOBS
# ------------------
jobs:
  build_and_scan:
    executor: build-executor
    steps:
      - checkout:
          path: ~/laa-crime-hardship
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean build
      - run:
          name: Run SonarQube
          command: ./gradlew sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.organization=${SONAR_ORG}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports/jacoco/test/html
      - store_artifacts:
          path: build/libs
      - snyk/scan:
          <<: *snyk_options

  build_scan_and_push_image:
    executor: aws-ecr/default # use the aws-ecr/default executor to start the docker daemon
    steps:
      # Checkout GitHub repository
      - uses: actions/checkout@v3

      # Assume role in Cloud Platform
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      # Login to container repository
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      # Build and push a Docker image to the container repository
      - run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
#    steps:
#      - checkout:
#          path: ~/laa-crime-hardship
#      - attach_workspace:
#          at: .
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run:
#          name: Build docker image
#          command: |
#            docker build \
#            --build-arg COMMIT_ID=${CIRCLE_SHA1} \
#            --build-arg BUILD_TAG=${CIRCLE_SHA1} \
#            --build-arg APP_BRANCH=${CIRCLE_BRANCH} \
#            --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S%z) \
#            -t $AWS_ECR_ACCOUNT_URL/laa-crime-apps-team/laa-crime-hardship-dev:${CIRCLE_SHA1} .
#      - snyk/scan:
#          docker-image-name: "$AWS_ECR_ACCOUNT_URL/laa-crime-apps-team/laa-crime-hardship-dev:${CIRCLE_SHA1}"
#          <<: *snyk_options
#      - run:
#          name: Push to ECR
#          command: |
#            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#            unzip awscliv2.zip
#            sudo ./aws/install
#            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
#            docker push "$AWS_ECR_ACCOUNT_URL/laa-crime-apps-team/laa-crime-hardship-dev:${CIRCLE_SHA1}"

  deploy-dev:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: dev
          token: ${CIRCLE_CI_TOKEN_DEV}

  deploy-test:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: test
          token: ${CIRCLE_CI_TOKEN_TEST}

  deploy-uat:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: uat
          token: ${CIRCLE_CI_TOKEN_UAT}

  deploy-staging:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: staging
          token: ${CIRCLE_CI_TOKEN_STAGING}

  deploy-prod:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: prod
          token: ${CIRCLE_CI_TOKEN_PROD}

# ------------------
# WORKFLOWS
# ------------------
workflows:
  version: 2

  build-deploy-master:
    jobs:
      - build_and_scan:
          context: build-deploy-master-workflow
          filters:
            branches:
              only:
                - main

      - build_scan_and_push_image:
          context: build-deploy-master-workflow
          requires:
            - build_and_scan

      - deploy-dev:
          context: build-deploy-master-workflow
          requires:
            - build_scan_and_push_image

      - hold_install_on_test:
          context: build-deploy-master-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-test:
          context: build-deploy-master-workflow
          requires:
            - hold_install_on_test

      - hold_install_on_uat:
          context: build-deploy-master-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-uat:
          context: build-deploy-master-workflow
          requires:
            - hold_install_on_uat

      - hold_install_on_staging:
          context: build-deploy-master-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-staging:
          context: build-deploy-master-workflow
          requires:
            - hold_install_on_staging

      - hold_install_on_prod:
          context: build-deploy-master-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-prod:
          context: build-deploy-master-workflow
          requires:
            - hold_install_on_prod

  build-deploy-branch:
    jobs:
      - build_and_scan:
          context: build-deploy-branch-workflow
          filters:
            branches:
              ignore:
                - main

      - build_scan_and_push_image:
          context: build-deploy-branch-workflow
          requires:
            - build_and_scan

      - hold_install_on_dev:
          context: build-deploy-branch-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-dev:
          context: build-deploy-branch-workflow
          requires:
            - hold_install_on_dev

      - hold_install_on_test:
          context: build-deploy-branch-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-test:
          context: build-deploy-branch-workflow
          requires:
            - hold_install_on_test

      - hold_install_on_uat:
          context: build-deploy-branch-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-uat:
          context: build-deploy-branch-workflow
          requires:
            - hold_install_on_uat

      - hold_install_on_staging:
          context: build-deploy-branch-workflow
          type: approval
          requires:
            - build_scan_and_push_image

      - deploy-staging:
          context: build-deploy-branch-workflow
          requires:
            - hold_install_on_staging
