--liquibase formatted sql
--changeset muthus:02-hardship-review-detail-reasons-table-create
CREATE TABLE IF NOT EXISTS crime_hardship.HARDSHIP_REVIEW_DETAIL_REASONS
(
    ID INTEGER,
    REASON VARCHAR(200) NOT NULL,
    HRDT_TYPE VARCHAR(15) NOT NULL,
    FORCE_NOTE VARCHAR(1),
    DATE_CREATED TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_CREATED VARCHAR(100) DEFAULT user NOT NULL,
    DATE_MODIFIED TIMESTAMP (6),
    USER_MODIFIED VARCHAR(100),
    ACCEPTED VARCHAR(1)
    UNIQUE (HRDT_TYPE, REASON)
    CONSTRAINT hrdr_pk PRIMARY KEY (ID)
);